name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run build
      - run: echo GITHUB ACTION RUN BUILD
